name: HostnameGate
version: '1.0'
main: me.mikinol.hostnamegate.HostnameGatePlugin
author: "mikinol"
api-version: '1.20'
bootstrapper: me.mikinol.hostnamegate.HostnameGateBootstrap
loader: me.mikinol.hostnamegate.HostnameGateLoader

permissions:
  hostnamegate.reload:
    description: "Allows to reload plugin"
    default: op